### PR TITLE
Major bug fix and QOL changes.

### PR DESCRIPTION
**Pull request by StuxxyOfficial**
- Fix vehicle props/plate/health being set incorrectly or failing to set.
- we now store the vehicledata in a statebag then on clients we have a statebag change handler listening, if the entity owner doesn't equal that player then we return end. else we apply vehicle mods and vehicle damage etc. once mods are applied we then tell the server to update the vehicle in the database.
- Save fuel in health column, compatibility with current scripts and ox_fuel afaik.
- Add lastgarage column to sql file for use with restore vehicles on restart and split garages
- Fix livery and extra's not being saved correctly
- Fix Blown up vehicles not appearing in the impound. if vehicle does exist but is blown up, the impound will delete the blown up one when a player checks the impound.
- Fix canAfford function when using bank instead of cash.

### CODE REVIEW

**Comment by LukeWasTakenn** [comment]
Are the get and set props functions directly off of ox_lib or modified a bit?

**Comment by StuxxyOfficial** [comment]
> Are the get and set props functions directly off of ox_lib or modified a bit?

they are modified slightly. mainly just to fix extra's not saving correctly and of course setting fuel level. im sure you could put the code outside of that function and use the lib. but i didn't want to add any extra dependencies.

**Comment by LukeWasTakenn** [comment]
Since I'll be adding a context menu to ox_lib, I'll probably just end up ditching zf_context and using that honestly

**Comment by StuxxyOfficial** [comment]
Changes made as requested :)

**Review by LukeWasTakenn — APPROVED** [review]

**Pull request merged**
