### PR TITLE
Config option for society jobgarage

### PR DESCRIPTION
**Pull request by Vumono**
Added config option for jobgarages to have a 'shared' garage containing all vehicles in that garage by people with the job

### CODE REVIEW

**Comment by LukeWasTakenn** [comment]
Wouldn't this just cause issues where a player can take out another player's owned vehicle?

**Comment by Vumono** [comment]
I dont think it will be an issue because then it's society vehicles. So all job vehicles are society owned. Might become an issue when in impounds tho, was going to have a look at it later again for a better way or config option per 'job' garage

**Comment by Vumono** [comment]
Yes, fixed the impounding and added the option for people with same job to put away the vehicle in the garage

**Comment by Vumono** [comment]
As you said tho, all people with same job will be able to pull out all the jobvehicles. That's why it's society jobgarage

**Comment by LukeWasTakenn** [comment]
> As you said tho, all people with same job will be able to pull out all the jobvehicles. That's why it's society jobgarage

I feel like that kind of defeats the point of owning a job vehicle if someone else can pull your own vehicle out and stuff.

**Comment by Vumono** [comment]
Well, I think we might have a different understanding of a job vehicle. What Im using the job vehicle garage for is purely to have jobs like police and ambulance have only a couple vehicles in their garage for everybody to use. Which opens up the possibility for police to earn money and invest in better/more cars and such. But I understand that's not something everybody wants on their server

**Comment by Marc85BPG** [comment]
in a job, like ambulance/police, doj, etc. you should not be the "owner"...the "owner is the hospital-police station. you work in this job, so everyone should take a vehicle out like vumono did this. so i totally agree what vumono said :)

**Comment by LukeWasTakenn** [comment]
I think I'll do this as a base option then, instead of it being a config option

**Review by LukeWasTakenn — CHANGES_REQUESTED** [review]
Remove the config option and add it as a base

**Pull request closed without merging**
